In [1]:
# WORKING OF A PERCEPTRON
import numpy as np
x= np.array([[0,0],[0,1],[1,0],[1,1]])
y= np.array([0,1,1,1])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [2]:
y

array([0, 1, 1, 1])

In [3]:
# weights
w= np.array([1,1])
# bias
b= -0.05

In [4]:
def activation(z):
    if z >= 0:
        return 1
    else:
        return 0

In [5]:
pred =[]
for a in x:
    y_hat = np.dot(a,w)+b
    pred.append(activation(y_hat))
    

In [6]:
pred

[0, 1, 1, 1]

PERCEPTRON LEARNING

In [7]:
import math

epochs = 100
alpha = 0.2


In [8]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()
print("Inintial Weights")

print('w0=',w0,"w1=",w1,"w2 =",w2)

Inintial Weights
w0= 0.3528901573256994 w1= 0.6085314090937243 w2 = 0.9719537837963601


In [9]:
del_w0 = 1
del_w1 = 1
del_w2 = 1

In [10]:
train_data_temp = [[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]
train_data = np.array(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [11]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [12]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

y= (x*w) + b

In [13]:
bias  = 0
for i in range(epochs):
    j =0
    for x in train_data:
        y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias

        if (y_hat >= 0):
            act =1
        else :
            act = 0
        
        err = op[j] -act

        del_w0 = alpha*x[0]*err
        del_w1 = alpha*x[1]*err
        del_w2 = alpha*x[2]*err

        w0= w0+ del_w0
        w1= w1+ del_w1
        w2= w2+ del_w2

        j = j+1
        print("epoch",i+1 , "error = ",err)
        print(del_w0,del_w1,del_w2)

print("\nFinal weights =")
print("w0 = ",w0,"w1 = ",w1,"w2 = ",w2)


epoch 1 error =  -1
-0.0 -0.0 -0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 1 error =  0
0.0 0.0 0.0
epoch 2 error =  -1
-0.0 -0.0 -0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 2 error =  0
0.0 0.0 0.0
epoch 3 error =  -1
-0.0 -0.0 -0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 3 error =  0
0.0 0.0 0.0
epoch 4 error =  -1
-0.0 -0.0 -0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 0.0 0.0
epoch 4 error =  0
0.0 

TYPES OF CLASSIFICATION

1.Binary Classification
  Two classes: Normal class:0
               Aberrant class:1
2.MultiClass Classification
   Data are grouped into several well known classes.

3.MultiLabeled Classification
 features more than two class labels
4.Imbalanced Classification
 Each class has different distribution


LEARNER TYPE TERMINOLOGY
1.Lazy Learner(Instance based learning)
 Delays the generalization of training data until a query is made to the system. eg KNN & Case Based Reasoning

2.Eager Learner
 Before obtaining a test dataset, earger learners build a classification model using a training dataset.Eg :ANN , Naive Bayes
 
 



Scikit Learn Classification Algorithms

KNN ALGORITHM
-K stands for the number of neighbours we choose 
-Adjusting K is termed as parameter tuning

When To Use KNN
-Data is properly labeled
-Data should be noise free
-Works very well on small scale datasets
-Is better when you want to create models with higher accuracy on cost of computational resources


 
 

In [14]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import datasets
data = datasets.load_wine(as_frame=True)
data

{'data':      alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
 0      14.23        1.71  2.43               15.6      127.0           2.80   
 1      13.20        1.78  2.14               11.2      100.0           2.65   
 2      13.16        2.36  2.67               18.6      101.0           2.80   
 3      14.37        1.95  2.50               16.8      113.0           3.85   
 4      13.24        2.59  2.87               21.0      118.0           2.80   
 ..       ...         ...   ...                ...        ...            ...   
 173    13.71        5.65  2.45               20.5       95.0           1.68   
 174    13.40        3.91  2.48               23.0      102.0           1.80   
 175    13.27        4.28  2.26               20.0      120.0           1.59   
 176    13.17        2.59  2.37               20.0      120.0           1.65   
 177    14.13        4.10  2.74               24.5       96.0           2.05   
 
      flavanoids  nonflavanoid

In [15]:
X = data.data
y = data.target
names = data.target_names
print(names)

['class_0' 'class_1' 'class_2']


In [16]:
df = pd.DataFrame(x,columns=data.feature_names)
df['wine class'] = data.target
df['wine class'] = df['wine class'].replace(to_replace=[0,1,2],value= ['class_0','class_1','class_2'])

ValueError: Shape of passed values is (3, 1), indices imply (3, 13)

In [ ]:
df

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,wine class
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,class_0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,class_0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,class_0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,class_0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,class_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740.0,class_2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750.0,class_2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835.0,class_2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840.0,class_2


In [ ]:
sns.pairplot(data= df,hue='wine class' ,palette='Set2')

In [ ]:
df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
wine class                      0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state= 42)

InvalidParameterError: The 'random_state' parameter of train_test_split must be an int in the range [0, 4294967295], an instance of 'numpy.random.mtrand.RandomState' or None. Got 0.3 instead.